/*!
 *****************************************************************************
 *
 * @File       msvdx_test_3_regs.h
 * @Description    This file contains the MSVDX_TEST_3_REGS_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_TEST_3_REGS_H__)
#define __MSVDX_TEST_3_REGS_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_OFFSET		(0x0050)

/* MSVDX_TEST_3, SECURE_MEM_CTRL_0, MEM_PROTECT_ENABLE
*/
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_PROTECT_ENABLE_MASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_PROTECT_ENABLE_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_PROTECT_ENABLE_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_PROTECT_ENABLE_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_PROTECT_ENABLE_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_PROTECT_ENABLE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_MEM_CTRL_0, MEM_CAPTURE_LAST_ERROR
*/
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_CAPTURE_LAST_ERROR_MASK		(0x00000002)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_CAPTURE_LAST_ERROR_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_CAPTURE_LAST_ERROR_SHIFT		(1)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_CAPTURE_LAST_ERROR_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_CAPTURE_LAST_ERROR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_CAPTURE_LAST_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_MEM_CTRL_0, MEM_LOCKUP_ENABLE
*/
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_LOCKUP_ENABLE_MASK		(0x00000010)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_LOCKUP_ENABLE_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_LOCKUP_ENABLE_SHIFT		(4)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_LOCKUP_ENABLE_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_LOCKUP_ENABLE_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_MEM_LOCKUP_ENABLE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_MEM_CTRL_0, SECURE_MEM_BOUNDARY
*/
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_SECURE_MEM_BOUNDARY_MASK		(0xFFFFF000)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_SECURE_MEM_BOUNDARY_LSBMASK		(0x000FFFFF)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_SECURE_MEM_BOUNDARY_SHIFT		(12)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_SECURE_MEM_BOUNDARY_LENGTH		(20)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_SECURE_MEM_BOUNDARY_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_0_SECURE_MEM_BOUNDARY_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_OFFSET		(0x0054)

/* MSVDX_TEST_3, SECURE_MEM_CTRL_1, SECURE_MEM_CLEAR
*/
#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_SECURE_MEM_CLEAR_MASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_SECURE_MEM_CLEAR_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_SECURE_MEM_CLEAR_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_SECURE_MEM_CLEAR_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_SECURE_MEM_CLEAR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_CTRL_1_SECURE_MEM_CLEAR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_OFFSET		(0x0058)

/* MSVDX_TEST_3, SECURE_MEM_STATUS_0, SECURE_MEM_ERROR
*/
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_MASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_MEM_STATUS_0, SECURE_MEM_ERROR_RNW
*/
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_RNW_MASK		(0x00000010)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_RNW_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_RNW_SHIFT		(4)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_RNW_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_RNW_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_RNW_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_MEM_STATUS_0, SECURE_MEM_ERROR_TAG_ID
*/
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_ID_MASK		(0x00FF0000)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_ID_LSBMASK		(0x000000FF)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_ID_SHIFT		(16)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_ID_LENGTH		(8)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_ID_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_ID_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_MEM_STATUS_0, SECURE_MEM_ERROR_TAG_SB
*/
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_SB_MASK		(0xFF000000)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_SB_LSBMASK		(0x000000FF)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_SB_SHIFT		(24)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_SB_LENGTH		(8)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_SB_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_0_SECURE_MEM_ERROR_TAG_SB_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_OFFSET		(0x005C)

/* MSVDX_TEST_3, SECURE_MEM_STATUS_1, SECURE_MEM_ERROR_ADDR
*/
#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_SECURE_MEM_ERROR_ADDR_MASK		(0xFFFFFFFF)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_SECURE_MEM_ERROR_ADDR_LSBMASK		(0xFFFFFFFF)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_SECURE_MEM_ERROR_ADDR_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_SECURE_MEM_ERROR_ADDR_LENGTH		(32)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_SECURE_MEM_ERROR_ADDR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_MEM_STATUS_1_SECURE_MEM_ERROR_ADDR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_OFFSET		(0x0060)

/* MSVDX_TEST_3, SECURE_CPU_CTRL_0, SECURE_CPU_ENABLE
*/
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_ENABLE_MASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_ENABLE_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_ENABLE_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_ENABLE_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_ENABLE_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_ENABLE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_CPU_CTRL_0, SECURE_CPU_TRANSACTION
*/
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_TRANSACTION_MASK		(0x00000002)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_TRANSACTION_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_TRANSACTION_SHIFT		(1)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_TRANSACTION_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_TRANSACTION_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_0_SECURE_CPU_TRANSACTION_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_OFFSET		(0x0064)

/* MSVDX_TEST_3, SECURE_CPU_CTRL_1, SECURE_CPU_CLEAR
*/
#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_SECURE_CPU_CLEAR_MASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_SECURE_CPU_CLEAR_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_SECURE_CPU_CLEAR_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_SECURE_CPU_CLEAR_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_SECURE_CPU_CLEAR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_CPU_CTRL_1_SECURE_CPU_CLEAR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_OFFSET		(0x0068)

/* MSVDX_TEST_3, SECURE_CPU_STATUS_0, SECURE_CPU_ERROR
*/
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_MASK		(0x01000000)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_SHIFT		(24)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_CPU_STATUS_0, SECURE_CPU_ERROR_RNW
*/
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_RNW_MASK		(0x00100000)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_RNW_LSBMASK		(0x00000001)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_RNW_SHIFT		(20)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_RNW_LENGTH		(1)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_RNW_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_RNW_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_TEST_3, SECURE_CPU_STATUS_0, SECURE_CPU_ERROR_ADDR
*/
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_ADDR_MASK		(0x000FFFFF)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_ADDR_LSBMASK		(0x000FFFFF)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_ADDR_SHIFT		(0)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_ADDR_LENGTH		(20)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_ADDR_DEFAULT		(0)
#define MSVDX_TEST_3_SECURE_CPU_STATUS_0_SECURE_CPU_ERROR_ADDR_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_TEST_3_REGS_H__ */
