/*!
 *****************************************************************************
 *
 * @File       msvdx_vec_real_reg_io2.h
 * @Description    This file contains the MSVDX_VEC_REAL_REG_IO2_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_VEC_REAL_REG_IO2_H__)
#define __MSVDX_VEC_REAL_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_OFFSET		(0x0204)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_PIC0, REAL_FE_PIC_HEIGHT_IN_MBS_LESS1
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_HEIGHT_IN_MBS_LESS1_MASK		(0x00007F00)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_HEIGHT_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_HEIGHT_IN_MBS_LESS1_SHIFT		(8)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_HEIGHT_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_HEIGHT_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_HEIGHT_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_PIC0, REAL_FE_PIC_WIDTH_IN_MBS_LESS1
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_WIDTH_IN_MBS_LESS1_MASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_WIDTH_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_WIDTH_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_WIDTH_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_WIDTH_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_PIC0_REAL_FE_PIC_WIDTH_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_OFFSET		(0x0208)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE0, REAL_FE_NUM_MBS_IN_SLICE_LESS1
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_NUM_MBS_IN_SLICE_LESS1_MASK		(0x1FFF0000)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_NUM_MBS_IN_SLICE_LESS1_LSBMASK		(0x00001FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_NUM_MBS_IN_SLICE_LESS1_SHIFT		(16)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_NUM_MBS_IN_SLICE_LESS1_LENGTH		(13)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_NUM_MBS_IN_SLICE_LESS1_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_NUM_MBS_IN_SLICE_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE0, REAL_FE_FIRST_MB_IN_SLICE
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_FIRST_MB_IN_SLICE_MASK		(0x00001FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_FIRST_MB_IN_SLICE_LSBMASK		(0x00001FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_FIRST_MB_IN_SLICE_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_FIRST_MB_IN_SLICE_LENGTH		(13)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_FIRST_MB_IN_SLICE_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE0_REAL_FE_FIRST_MB_IN_SLICE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_OFFSET		(0x0210)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE1, REAL_FE_SLICE_START_Y
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_Y_MASK		(0x00007F00)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_Y_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_Y_SHIFT		(8)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_Y_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_Y_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_Y_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE1, REAL_FE_SLICE_START_X
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_X_MASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_X_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_X_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_X_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_X_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE1_REAL_FE_SLICE_START_X_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_OFFSET		(0x0224)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE2, REAL_FE_SLICE_QP
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_SLICE_QP_MASK		(0x00001F00)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_SLICE_QP_LSBMASK		(0x0000001F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_SLICE_QP_SHIFT		(8)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_SLICE_QP_LENGTH		(5)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_SLICE_QP_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_SLICE_QP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE2, REAL_FE_OSV_QUANT
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_OSV_QUANT_MASK		(0x00000030)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_OSV_QUANT_LSBMASK		(0x00000003)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_OSV_QUANT_SHIFT		(4)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_OSV_QUANT_LENGTH		(2)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_OSV_QUANT_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_OSV_QUANT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_FE_SLICE2, REAL_FE_PICTURE_TYPE
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_MASK		(0x00000003)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_LSBMASK		(0x00000003)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_LENGTH		(2)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_REAL_CR_VEC_REAL_FE_SLICE2_REAL_FE_PICTURE_TYPE_ENUM {
	MSVDX_VEC_REAL_REAL_FE_PICTURE_TYPE_RESERVED = 0x3,
	MSVDX_VEC_REAL_REAL_FE_PICTURE_TYPE_RV_TRUEBPIC = 0x2,
	MSVDX_VEC_REAL_REAL_FE_PICTURE_TYPE_RV_INTERPIC = 0x1,
	MSVDX_VEC_REAL_REAL_FE_PICTURE_TYPE_RV_INTRAPIC = 0x0,
};

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_OFFSET		(0x0250)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_PIC0, REAL_BE_PIC_HEIGHT_IN_MBS_LESS1
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_HEIGHT_IN_MBS_LESS1_MASK		(0x00007F00)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_HEIGHT_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_HEIGHT_IN_MBS_LESS1_SHIFT		(8)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_HEIGHT_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_HEIGHT_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_HEIGHT_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_PIC0, REAL_BE_PIC_WIDTH_IN_MBS_LESS1
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_WIDTH_IN_MBS_LESS1_MASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_WIDTH_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_WIDTH_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_WIDTH_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_WIDTH_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_PIC0_REAL_BE_PIC_WIDTH_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_OFFSET		(0x0254)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_SLICE0, REAL_BE_FIRST_MB_IN_SLICE
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_REAL_BE_FIRST_MB_IN_SLICE_MASK		(0x00001FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_REAL_BE_FIRST_MB_IN_SLICE_LSBMASK		(0x00001FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_REAL_BE_FIRST_MB_IN_SLICE_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_REAL_BE_FIRST_MB_IN_SLICE_LENGTH		(13)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_REAL_BE_FIRST_MB_IN_SLICE_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE0_REAL_BE_FIRST_MB_IN_SLICE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_OFFSET		(0x0258)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_SLICE1, REAL_BE_SLICE_START_Y
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_Y_MASK		(0x00007F00)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_Y_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_Y_SHIFT		(8)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_Y_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_Y_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_Y_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_SLICE1, REAL_BE_SLICE_START_X
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_X_MASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_X_LSBMASK		(0x0000007F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_X_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_X_LENGTH		(7)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_X_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE1_REAL_BE_SLICE_START_X_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_OFFSET		(0x025C)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_SLICE2, REAL_BE_SLICE_QP
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_SLICE_QP_MASK		(0x00001F00)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_SLICE_QP_LSBMASK		(0x0000001F)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_SLICE_QP_SHIFT		(8)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_SLICE_QP_LENGTH		(5)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_SLICE_QP_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_SLICE_QP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_SLICE2, REAL_BE_OSV_QUANT
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_OSV_QUANT_MASK		(0x00000030)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_OSV_QUANT_LSBMASK		(0x00000003)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_OSV_QUANT_SHIFT		(4)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_OSV_QUANT_LENGTH		(2)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_OSV_QUANT_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_OSV_QUANT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_SLICE2, REAL_BE_PICTURE_TYPE
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_PICTURE_TYPE_MASK		(0x00000003)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_PICTURE_TYPE_LSBMASK		(0x00000003)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_PICTURE_TYPE_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_PICTURE_TYPE_LENGTH		(2)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_PICTURE_TYPE_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_SLICE2_REAL_BE_PICTURE_TYPE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_OFFSET		(0x0260)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_IRATIO0, REAL_BE_IRATIO_0
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_REAL_BE_IRATIO_0_MASK		(0x00007FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_REAL_BE_IRATIO_0_LSBMASK		(0x00007FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_REAL_BE_IRATIO_0_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_REAL_BE_IRATIO_0_LENGTH		(15)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_REAL_BE_IRATIO_0_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO0_REAL_BE_IRATIO_0_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_OFFSET		(0x0264)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_IRATIO1, REAL_BE_IRATIO_1
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_REAL_BE_IRATIO_1_MASK		(0x00007FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_REAL_BE_IRATIO_1_LSBMASK		(0x00007FFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_REAL_BE_IRATIO_1_SHIFT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_REAL_BE_IRATIO_1_LENGTH		(15)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_REAL_BE_IRATIO_1_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_IRATIO1_REAL_BE_IRATIO_1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_OFFSET		(0x02EC)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC, REAL_BE_BASE_ADDR_CUR_PIC
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_REAL_BE_BASE_ADDR_CUR_PIC_MASK		(0xFFFFF000)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_REAL_BE_BASE_ADDR_CUR_PIC_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_REAL_BE_BASE_ADDR_CUR_PIC_SHIFT		(12)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_REAL_BE_BASE_ADDR_CUR_PIC_LENGTH		(20)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_REAL_BE_BASE_ADDR_CUR_PIC_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_CUR_PIC_REAL_BE_BASE_ADDR_CUR_PIC_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_OFFSET		(0x02F8)

/* MSVDX_VEC_REAL, CR_VEC_REAL_BE_BASE_ADDR_COL_PIC, REAL_BE_BASE_ADDR_COL_PIC
*/
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_REAL_BE_BASE_ADDR_COL_PIC_MASK		(0xFFFFF000)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_REAL_BE_BASE_ADDR_COL_PIC_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_REAL_BE_BASE_ADDR_COL_PIC_SHIFT		(12)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_REAL_BE_BASE_ADDR_COL_PIC_LENGTH		(20)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_REAL_BE_BASE_ADDR_COL_PIC_DEFAULT		(0)
#define MSVDX_VEC_REAL_CR_VEC_REAL_BE_BASE_ADDR_COL_PIC_REAL_BE_BASE_ADDR_COL_PIC_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_VEC_REAL_REG_IO2_H__ */
