/*!
 *****************************************************************************
 *
 * @File       msvdx_rendec_mpeg2_reg_io2.h
 * @Description    This file contains the MSVDX_RENDEC_MPEG2_REG_IO2_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_RENDEC_MPEG2_REG_IO2_H__)
#define __MSVDX_RENDEC_MPEG2_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MPEG2_RENDEC_CMD_MPEG2GEN00_OFFSET		(0x0000)

#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_OFFSET		(0x0004)

/* MPEG2_RENDEC_CMD, MPEG2SEQUENCE00, PICTURE_HEIGHT
*/
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_HEIGHT_MASK		(0x00FFF000)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_HEIGHT_LSBMASK		(0x00000FFF)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_HEIGHT_SHIFT		(12)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_HEIGHT_LENGTH		(12)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_HEIGHT_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_HEIGHT_SIGNED_FIELD	(IMG_FALSE)

/* MPEG2_RENDEC_CMD, MPEG2SEQUENCE00, PICTURE_WIDTH
*/
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_WIDTH_MASK		(0x00000FFF)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_WIDTH_LSBMASK		(0x00000FFF)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_WIDTH_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_WIDTH_LENGTH		(12)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_WIDTH_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE00_PICTURE_WIDTH_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2SEQUENCE01_OFFSET		(0x0008)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE00_OFFSET		(0x000C)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_OFFSET		(0x0010)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA00, QUANT_COEFFS_INTRA00
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_QUANT_COEFFS_INTRA00_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_QUANT_COEFFS_INTRA00_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_QUANT_COEFFS_INTRA00_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_QUANT_COEFFS_INTRA00_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_QUANT_COEFFS_INTRA00_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA00_QUANT_COEFFS_INTRA00_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_OFFSET		(0x0014)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA01, QUANT_COEFFS_INTRA01
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_QUANT_COEFFS_INTRA01_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_QUANT_COEFFS_INTRA01_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_QUANT_COEFFS_INTRA01_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_QUANT_COEFFS_INTRA01_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_QUANT_COEFFS_INTRA01_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA01_QUANT_COEFFS_INTRA01_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_OFFSET		(0x0018)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA02, QUANT_COEFFS_INTRA02
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_QUANT_COEFFS_INTRA02_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_QUANT_COEFFS_INTRA02_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_QUANT_COEFFS_INTRA02_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_QUANT_COEFFS_INTRA02_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_QUANT_COEFFS_INTRA02_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA02_QUANT_COEFFS_INTRA02_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_OFFSET		(0x001C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA03, QUANT_COEFFS_INTRA03
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_QUANT_COEFFS_INTRA03_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_QUANT_COEFFS_INTRA03_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_QUANT_COEFFS_INTRA03_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_QUANT_COEFFS_INTRA03_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_QUANT_COEFFS_INTRA03_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA03_QUANT_COEFFS_INTRA03_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_OFFSET		(0x0020)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA04, QUANT_COEFFS_INTRA04
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_QUANT_COEFFS_INTRA04_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_QUANT_COEFFS_INTRA04_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_QUANT_COEFFS_INTRA04_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_QUANT_COEFFS_INTRA04_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_QUANT_COEFFS_INTRA04_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA04_QUANT_COEFFS_INTRA04_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_OFFSET		(0x0024)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA05, QUANT_COEFFS_INTRA05
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_QUANT_COEFFS_INTRA05_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_QUANT_COEFFS_INTRA05_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_QUANT_COEFFS_INTRA05_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_QUANT_COEFFS_INTRA05_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_QUANT_COEFFS_INTRA05_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA05_QUANT_COEFFS_INTRA05_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_OFFSET		(0x0028)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA06, QUANT_COEFFS_INTRA06
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_QUANT_COEFFS_INTRA06_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_QUANT_COEFFS_INTRA06_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_QUANT_COEFFS_INTRA06_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_QUANT_COEFFS_INTRA06_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_QUANT_COEFFS_INTRA06_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA06_QUANT_COEFFS_INTRA06_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_OFFSET		(0x002C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA07, QUANT_COEFFS_INTRA07
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_QUANT_COEFFS_INTRA07_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_QUANT_COEFFS_INTRA07_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_QUANT_COEFFS_INTRA07_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_QUANT_COEFFS_INTRA07_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_QUANT_COEFFS_INTRA07_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA07_QUANT_COEFFS_INTRA07_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_OFFSET		(0x0030)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA08, QUANT_COEFFS_INTRA08
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_QUANT_COEFFS_INTRA08_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_QUANT_COEFFS_INTRA08_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_QUANT_COEFFS_INTRA08_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_QUANT_COEFFS_INTRA08_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_QUANT_COEFFS_INTRA08_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA08_QUANT_COEFFS_INTRA08_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_OFFSET		(0x0034)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA09, QUANT_COEFFS_INTRA09
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_QUANT_COEFFS_INTRA09_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_QUANT_COEFFS_INTRA09_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_QUANT_COEFFS_INTRA09_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_QUANT_COEFFS_INTRA09_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_QUANT_COEFFS_INTRA09_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA09_QUANT_COEFFS_INTRA09_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_OFFSET		(0x0038)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA10, QUANT_COEFFS_INTRA10
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_QUANT_COEFFS_INTRA10_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_QUANT_COEFFS_INTRA10_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_QUANT_COEFFS_INTRA10_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_QUANT_COEFFS_INTRA10_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_QUANT_COEFFS_INTRA10_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA10_QUANT_COEFFS_INTRA10_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_OFFSET		(0x003C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA11, QUANT_COEFFS_INTRA11
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_QUANT_COEFFS_INTRA11_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_QUANT_COEFFS_INTRA11_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_QUANT_COEFFS_INTRA11_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_QUANT_COEFFS_INTRA11_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_QUANT_COEFFS_INTRA11_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA11_QUANT_COEFFS_INTRA11_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_OFFSET		(0x0040)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA12, QUANT_COEFFS_INTRA12
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_QUANT_COEFFS_INTRA12_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_QUANT_COEFFS_INTRA12_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_QUANT_COEFFS_INTRA12_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_QUANT_COEFFS_INTRA12_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_QUANT_COEFFS_INTRA12_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA12_QUANT_COEFFS_INTRA12_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_OFFSET		(0x0044)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA13, QUANT_COEFFS_INTRA13
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_QUANT_COEFFS_INTRA13_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_QUANT_COEFFS_INTRA13_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_QUANT_COEFFS_INTRA13_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_QUANT_COEFFS_INTRA13_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_QUANT_COEFFS_INTRA13_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA13_QUANT_COEFFS_INTRA13_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_OFFSET		(0x0048)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA14, QUANT_COEFFS_INTRA14
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_QUANT_COEFFS_INTRA14_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_QUANT_COEFFS_INTRA14_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_QUANT_COEFFS_INTRA14_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_QUANT_COEFFS_INTRA14_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_QUANT_COEFFS_INTRA14_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA14_QUANT_COEFFS_INTRA14_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_OFFSET		(0x004C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_INTRA15, QUANT_COEFFS_INTRA15
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_QUANT_COEFFS_INTRA15_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_QUANT_COEFFS_INTRA15_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_QUANT_COEFFS_INTRA15_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_QUANT_COEFFS_INTRA15_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_QUANT_COEFFS_INTRA15_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_INTRA15_QUANT_COEFFS_INTRA15_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_OFFSET		(0x0050)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA00, QUANT_COEFFS_NONINTRA00
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_QUANT_COEFFS_NONINTRA00_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_QUANT_COEFFS_NONINTRA00_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_QUANT_COEFFS_NONINTRA00_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_QUANT_COEFFS_NONINTRA00_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_QUANT_COEFFS_NONINTRA00_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA00_QUANT_COEFFS_NONINTRA00_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_OFFSET		(0x0054)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA01, QUANT_COEFFS_NONINTRA01
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_QUANT_COEFFS_NONINTRA01_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_QUANT_COEFFS_NONINTRA01_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_QUANT_COEFFS_NONINTRA01_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_QUANT_COEFFS_NONINTRA01_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_QUANT_COEFFS_NONINTRA01_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA01_QUANT_COEFFS_NONINTRA01_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_OFFSET		(0x0058)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA02, QUANT_COEFFS_NONINTRA02
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_QUANT_COEFFS_NONINTRA02_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_QUANT_COEFFS_NONINTRA02_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_QUANT_COEFFS_NONINTRA02_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_QUANT_COEFFS_NONINTRA02_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_QUANT_COEFFS_NONINTRA02_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA02_QUANT_COEFFS_NONINTRA02_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_OFFSET		(0x005C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA03, QUANT_COEFFS_NONINTRA03
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_QUANT_COEFFS_NONINTRA03_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_QUANT_COEFFS_NONINTRA03_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_QUANT_COEFFS_NONINTRA03_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_QUANT_COEFFS_NONINTRA03_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_QUANT_COEFFS_NONINTRA03_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA03_QUANT_COEFFS_NONINTRA03_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_OFFSET		(0x0060)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA04, QUANT_COEFFS_NONINTRA04
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_QUANT_COEFFS_NONINTRA04_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_QUANT_COEFFS_NONINTRA04_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_QUANT_COEFFS_NONINTRA04_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_QUANT_COEFFS_NONINTRA04_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_QUANT_COEFFS_NONINTRA04_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA04_QUANT_COEFFS_NONINTRA04_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_OFFSET		(0x0064)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA05, QUANT_COEFFS_NONINTRA05
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_QUANT_COEFFS_NONINTRA05_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_QUANT_COEFFS_NONINTRA05_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_QUANT_COEFFS_NONINTRA05_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_QUANT_COEFFS_NONINTRA05_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_QUANT_COEFFS_NONINTRA05_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA05_QUANT_COEFFS_NONINTRA05_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_OFFSET		(0x0068)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA06, QUANT_COEFFS_NONINTRA06
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_QUANT_COEFFS_NONINTRA06_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_QUANT_COEFFS_NONINTRA06_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_QUANT_COEFFS_NONINTRA06_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_QUANT_COEFFS_NONINTRA06_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_QUANT_COEFFS_NONINTRA06_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA06_QUANT_COEFFS_NONINTRA06_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_OFFSET		(0x006C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA07, QUANT_COEFFS_NONINTRA07
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_QUANT_COEFFS_NONINTRA07_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_QUANT_COEFFS_NONINTRA07_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_QUANT_COEFFS_NONINTRA07_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_QUANT_COEFFS_NONINTRA07_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_QUANT_COEFFS_NONINTRA07_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA07_QUANT_COEFFS_NONINTRA07_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_OFFSET		(0x0070)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA08, QUANT_COEFFS_NONINTRA08
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_QUANT_COEFFS_NONINTRA08_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_QUANT_COEFFS_NONINTRA08_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_QUANT_COEFFS_NONINTRA08_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_QUANT_COEFFS_NONINTRA08_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_QUANT_COEFFS_NONINTRA08_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA08_QUANT_COEFFS_NONINTRA08_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_OFFSET		(0x0074)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA09, QUANT_COEFFS_NONINTRA09
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_QUANT_COEFFS_NONINTRA09_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_QUANT_COEFFS_NONINTRA09_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_QUANT_COEFFS_NONINTRA09_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_QUANT_COEFFS_NONINTRA09_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_QUANT_COEFFS_NONINTRA09_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA09_QUANT_COEFFS_NONINTRA09_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_OFFSET		(0x0078)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA10, QUANT_COEFFS_NONINTRA10
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_QUANT_COEFFS_NONINTRA10_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_QUANT_COEFFS_NONINTRA10_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_QUANT_COEFFS_NONINTRA10_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_QUANT_COEFFS_NONINTRA10_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_QUANT_COEFFS_NONINTRA10_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA10_QUANT_COEFFS_NONINTRA10_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_OFFSET		(0x007C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA11, QUANT_COEFFS_NONINTRA11
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_QUANT_COEFFS_NONINTRA11_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_QUANT_COEFFS_NONINTRA11_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_QUANT_COEFFS_NONINTRA11_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_QUANT_COEFFS_NONINTRA11_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_QUANT_COEFFS_NONINTRA11_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA11_QUANT_COEFFS_NONINTRA11_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_OFFSET		(0x0080)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA12, QUANT_COEFFS_NONINTRA12
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_QUANT_COEFFS_NONINTRA12_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_QUANT_COEFFS_NONINTRA12_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_QUANT_COEFFS_NONINTRA12_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_QUANT_COEFFS_NONINTRA12_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_QUANT_COEFFS_NONINTRA12_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA12_QUANT_COEFFS_NONINTRA12_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_OFFSET		(0x0084)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA13, QUANT_COEFFS_NONINTRA13
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_QUANT_COEFFS_NONINTRA13_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_QUANT_COEFFS_NONINTRA13_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_QUANT_COEFFS_NONINTRA13_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_QUANT_COEFFS_NONINTRA13_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_QUANT_COEFFS_NONINTRA13_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA13_QUANT_COEFFS_NONINTRA13_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_OFFSET		(0x0088)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA14, QUANT_COEFFS_NONINTRA14
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_QUANT_COEFFS_NONINTRA14_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_QUANT_COEFFS_NONINTRA14_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_QUANT_COEFFS_NONINTRA14_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_QUANT_COEFFS_NONINTRA14_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_QUANT_COEFFS_NONINTRA14_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA14_QUANT_COEFFS_NONINTRA14_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_OFFSET		(0x008C)

/* MPEG2_RENDEC_CMD, MPEG2PICTURE_QUANT_NONINTRA15, QUANT_COEFFS_NONINTRA15
*/
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_QUANT_COEFFS_NONINTRA15_MASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_QUANT_COEFFS_NONINTRA15_LSBMASK		(0xFFFFFFFF)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_QUANT_COEFFS_NONINTRA15_SHIFT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_QUANT_COEFFS_NONINTRA15_LENGTH		(32)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_QUANT_COEFFS_NONINTRA15_DEFAULT		(0)
#define MPEG2_RENDEC_CMD_MPEG2PICTURE_QUANT_NONINTRA15_QUANT_COEFFS_NONINTRA15_SIGNED_FIELD	(IMG_FALSE)

#define MPEG2_RENDEC_CMD_MPEG2SLICE00_OFFSET		(0x0090)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_RENDEC_MPEG2_REG_IO2_H__ */
