/*!
 *****************************************************************************
 *
 * @File       msvdx_vec_avs_reg_io2.h
 * @Description    This file contains the MSVDX_VEC_AVS_REG_IO2_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_VEC_AVS_REG_IO2_H__)
#define __MSVDX_VEC_AVS_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_OFFSET		(0x0700)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC0, AVS_FE_PICTURETYPE
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURETYPE_MASK		(0x00000C00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURETYPE_LSBMASK		(0x00000003)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURETYPE_SHIFT		(10)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURETYPE_LENGTH		(2)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURETYPE_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURETYPE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC0, AVS_FE_PICTURE_STRUCTURE
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_STRUCTURE_MASK		(0x00000200)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_STRUCTURE_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_STRUCTURE_SHIFT		(9)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_STRUCTURE_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_STRUCTURE_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_STRUCTURE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC0, AVS_FE_SKIP_MODE_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_SKIP_MODE_FLAG_MASK		(0x00000100)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_SKIP_MODE_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_SKIP_MODE_FLAG_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_SKIP_MODE_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_SKIP_MODE_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_SKIP_MODE_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC0, AVS_FE_PICTURE_REFERENCE_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_REFERENCE_FLAG_MASK		(0x00000080)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_REFERENCE_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_REFERENCE_FLAG_SHIFT		(7)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_REFERENCE_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_REFERENCE_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_PICTURE_REFERENCE_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC0, AVS_FE_FIXED_PICTURE_QP
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_FIXED_PICTURE_QP_MASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_FIXED_PICTURE_QP_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_FIXED_PICTURE_QP_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_FIXED_PICTURE_QP_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_FIXED_PICTURE_QP_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC0_AVS_FE_FIXED_PICTURE_QP_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_OFFSET		(0x0704)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC1, AVS_FE_PICHEIGHTINMBSLESS1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICHEIGHTINMBSLESS1_MASK		(0x0000FF00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICHEIGHTINMBSLESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICHEIGHTINMBSLESS1_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICHEIGHTINMBSLESS1_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICHEIGHTINMBSLESS1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICHEIGHTINMBSLESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC1, AVS_FE_PICWIDTHINMBSLESS1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICWIDTHINMBSLESS1_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICWIDTHINMBSLESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICWIDTHINMBSLESS1_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICWIDTHINMBSLESS1_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICWIDTHINMBSLESS1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC1_AVS_FE_PICWIDTHINMBSLESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_OFFSET		(0x0708)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_PIC2, AVS_FE_PICSIZEINMBSLESS1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_AVS_FE_PICSIZEINMBSLESS1_MASK		(0x0000FFFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_AVS_FE_PICSIZEINMBSLESS1_LSBMASK		(0x0000FFFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_AVS_FE_PICSIZEINMBSLESS1_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_AVS_FE_PICSIZEINMBSLESS1_LENGTH		(16)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_AVS_FE_PICSIZEINMBSLESS1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_PIC2_AVS_FE_PICSIZEINMBSLESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_OFFSET		(0x0710)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_FIRST_MB_IN_SLICE
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_MASK		(0x7FFE0000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_LSBMASK		(0x00003FFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_SHIFT		(17)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_LENGTH		(14)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_FIRST_MB_IN_SLICE_EXT
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_EXT_MASK		(0x00001800)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_EXT_LSBMASK		(0x00000003)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_EXT_SHIFT		(11)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_EXT_LENGTH		(2)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_EXT_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_EXT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_FIRST_MB_IN_SLICE_Y_EXT
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_EXT_MASK		(0x00000400)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_EXT_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_EXT_SHIFT		(10)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_EXT_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_EXT_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_EXT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_FIXED_SLICE_QP
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIXED_SLICE_QP_MASK		(0x00000200)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIXED_SLICE_QP_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIXED_SLICE_QP_SHIFT		(9)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIXED_SLICE_QP_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIXED_SLICE_QP_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIXED_SLICE_QP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_MB_WEIGHTING_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_MB_WEIGHTING_FLAG_MASK		(0x00000100)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_MB_WEIGHTING_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_MB_WEIGHTING_FLAG_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_MB_WEIGHTING_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_MB_WEIGHTING_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_MB_WEIGHTING_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_SLICE_WEIGHTING_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_SLICE_WEIGHTING_FLAG_MASK		(0x00000080)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_SLICE_WEIGHTING_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_SLICE_WEIGHTING_FLAG_SHIFT		(7)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_SLICE_WEIGHTING_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_SLICE_WEIGHTING_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_SLICE_WEIGHTING_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_FE_SLICE0, AVS_FE_FIRST_MB_IN_SLICE_Y
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_MASK		(0x0000007F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_LSBMASK		(0x0000007F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_LENGTH		(7)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_FE_SLICE0_AVS_FE_FIRST_MB_IN_SLICE_Y_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_OFFSET		(0x0750)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_TOP_FIELD_1ST
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_TOP_FIELD_1ST_MASK		(0x00002000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_TOP_FIELD_1ST_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_TOP_FIELD_1ST_SHIFT		(13)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_TOP_FIELD_1ST_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_TOP_FIELD_1ST_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_TOP_FIELD_1ST_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_PROGRESSIVE_FRAME
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PROGRESSIVE_FRAME_MASK		(0x00001000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PROGRESSIVE_FRAME_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PROGRESSIVE_FRAME_SHIFT		(12)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PROGRESSIVE_FRAME_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PROGRESSIVE_FRAME_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PROGRESSIVE_FRAME_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_PICTURETYPE
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURETYPE_MASK		(0x00000C00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURETYPE_LSBMASK		(0x00000003)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURETYPE_SHIFT		(10)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURETYPE_LENGTH		(2)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURETYPE_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURETYPE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_PICTURE_STRUCTURE
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_STRUCTURE_MASK		(0x00000200)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_STRUCTURE_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_STRUCTURE_SHIFT		(9)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_STRUCTURE_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_STRUCTURE_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_STRUCTURE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_SKIP_MODE_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_SKIP_MODE_FLAG_MASK		(0x00000100)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_SKIP_MODE_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_SKIP_MODE_FLAG_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_SKIP_MODE_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_SKIP_MODE_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_SKIP_MODE_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_PICTURE_REFERENCE_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_REFERENCE_FLAG_MASK		(0x00000080)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_REFERENCE_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_REFERENCE_FLAG_SHIFT		(7)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_REFERENCE_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_REFERENCE_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_REFERENCE_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_PICTURE_QP
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_QP_MASK		(0x0000007E)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_QP_LSBMASK		(0x0000003F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_QP_SHIFT		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_QP_LENGTH		(6)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_QP_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_PICTURE_QP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC0, AVS_BE_FIXED_PICTURE_QP
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_FIXED_PICTURE_QP_MASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_FIXED_PICTURE_QP_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_FIXED_PICTURE_QP_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_FIXED_PICTURE_QP_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_FIXED_PICTURE_QP_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC0_AVS_BE_FIXED_PICTURE_QP_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_OFFSET		(0x0754)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC1, AVS_BE_PICHEIGHTINMBSLESS1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICHEIGHTINMBSLESS1_MASK		(0x0000FF00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICHEIGHTINMBSLESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICHEIGHTINMBSLESS1_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICHEIGHTINMBSLESS1_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICHEIGHTINMBSLESS1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICHEIGHTINMBSLESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC1, AVS_BE_PICWIDTHINMBSLESS1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICWIDTHINMBSLESS1_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICWIDTHINMBSLESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICWIDTHINMBSLESS1_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICWIDTHINMBSLESS1_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICWIDTHINMBSLESS1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC1_AVS_BE_PICWIDTHINMBSLESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_OFFSET		(0x0758)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC2, AVS_BE_PICSIZEINMBSLESS1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_AVS_BE_PICSIZEINMBSLESS1_MASK		(0x0000FFFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_AVS_BE_PICSIZEINMBSLESS1_LSBMASK		(0x0000FFFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_AVS_BE_PICSIZEINMBSLESS1_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_AVS_BE_PICSIZEINMBSLESS1_LENGTH		(16)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_AVS_BE_PICSIZEINMBSLESS1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC2_AVS_BE_PICSIZEINMBSLESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_OFFSET		(0x075C)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_REF1_0, AVS_BE_PIC_DIST_REF1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF1_MASK		(0x0000FF00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF1_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF1_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_REF1_0, AVS_BE_PIC_DIST_REF0
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF0_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF0_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF0_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF0_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF0_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF1_0_AVS_BE_PIC_DIST_REF0_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_OFFSET		(0x0760)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_REF2_3, AVS_BE_PIC_DIST_REF3
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF3_MASK		(0x0000FF00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF3_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF3_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF3_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF3_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF3_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_REF2_3, AVS_BE_PIC_DIST_REF2
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF2_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF2_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF2_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF2_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF2_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_REF2_3_AVS_BE_PIC_DIST_REF2_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_OFFSET		(0x0764)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_CURR, AVS_BE_PIC_DIST_CURR
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_AVS_BE_PIC_DIST_CURR_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_AVS_BE_PIC_DIST_CURR_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_AVS_BE_PIC_DIST_CURR_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_AVS_BE_PIC_DIST_CURR_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_AVS_BE_PIC_DIST_CURR_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_CURR_AVS_BE_PIC_DIST_CURR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_OFFSET		(0x0768)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_BW_REF1_0, AVS_BE_PIC_DIST_BW_REF1
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF1_MASK		(0x0000FF00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF1_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF1_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF1_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_BW_REF1_0, AVS_BE_PIC_DIST_BW_REF0
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF0_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF0_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF0_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF0_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF0_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF1_0_AVS_BE_PIC_DIST_BW_REF0_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_OFFSET		(0x076C)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_BW_REF3_2, AVS_BE_PIC_DIST_BW_REF3
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF3_MASK		(0x0000FF00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF3_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF3_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF3_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF3_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF3_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_DIST_BW_REF3_2, AVS_BE_PIC_DIST_BW_REF2
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF2_MASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF2_LSBMASK		(0x000000FF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF2_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF2_LENGTH		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF2_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_DIST_BW_REF3_2_AVS_BE_PIC_DIST_BW_REF2_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_OFFSET		(0x0770)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC_STRUCT, AVS_BE_PIC_STRUCT_REF
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_REF_MASK		(0x0000000F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_REF_LSBMASK		(0x0000000F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_REF_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_REF_LENGTH		(4)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_REF_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_REF_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_PIC_STRUCT, AVS_BE_PIC_STRUCT_BW_REF
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_BW_REF_MASK		(0x000000F0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_BW_REF_LSBMASK		(0x0000000F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_BW_REF_SHIFT		(4)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_BW_REF_LENGTH		(4)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_BW_REF_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_PIC_STRUCT_AVS_BE_PIC_STRUCT_BW_REF_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_OFFSET		(0x0774)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_FIRST_MB_IN_SLICE_Y_EXT
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_EXT_MASK		(0x00020000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_EXT_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_EXT_SHIFT		(17)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_EXT_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_EXT_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_EXT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_CURR_BFF
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_CURR_BFF_MASK		(0x00010000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_CURR_BFF_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_CURR_BFF_SHIFT		(16)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_CURR_BFF_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_CURR_BFF_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_CURR_BFF_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_SLICE_QP
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_QP_MASK		(0x0000FC00)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_QP_LSBMASK		(0x0000003F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_QP_SHIFT		(10)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_QP_LENGTH		(6)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_QP_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_QP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_FIXED_SLICE_QP
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIXED_SLICE_QP_MASK		(0x00000200)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIXED_SLICE_QP_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIXED_SLICE_QP_SHIFT		(9)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIXED_SLICE_QP_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIXED_SLICE_QP_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIXED_SLICE_QP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_MB_WEIGHTING_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_MB_WEIGHTING_FLAG_MASK		(0x00000100)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_MB_WEIGHTING_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_MB_WEIGHTING_FLAG_SHIFT		(8)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_MB_WEIGHTING_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_MB_WEIGHTING_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_MB_WEIGHTING_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_SLICE_WEIGHTING_FLAG
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_WEIGHTING_FLAG_MASK		(0x00000080)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_WEIGHTING_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_WEIGHTING_FLAG_SHIFT		(7)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_WEIGHTING_FLAG_LENGTH		(1)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_WEIGHTING_FLAG_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_SLICE_WEIGHTING_FLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE0, AVS_BE_FIRST_MB_IN_SLICE_Y
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_MASK		(0x0000007F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_LSBMASK		(0x0000007F)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_LENGTH		(7)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE0_AVS_BE_FIRST_MB_IN_SLICE_Y_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_OFFSET		(0x0778)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_SLICE1, AVS_BE_SLICE_FIELD_TYPE
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_AVS_BE_SLICE_FIELD_TYPE_MASK		(0x00000003)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_AVS_BE_SLICE_FIELD_TYPE_LSBMASK		(0x00000003)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_AVS_BE_SLICE_FIELD_TYPE_SHIFT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_AVS_BE_SLICE_FIELD_TYPE_LENGTH		(2)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_AVS_BE_SLICE_FIELD_TYPE_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_SLICE1_AVS_BE_SLICE_FIELD_TYPE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_OFFSET		(0x07EC)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC, AVS_CURRPIC_PARAMS_BASE_ADDRESS
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_AVS_CURRPIC_PARAMS_BASE_ADDRESS_MASK		(0xFFFFF000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_AVS_CURRPIC_PARAMS_BASE_ADDRESS_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_AVS_CURRPIC_PARAMS_BASE_ADDRESS_SHIFT		(12)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_AVS_CURRPIC_PARAMS_BASE_ADDRESS_LENGTH		(20)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_AVS_CURRPIC_PARAMS_BASE_ADDRESS_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_CUR_PIC_AVS_CURRPIC_PARAMS_BASE_ADDRESS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_OFFSET		(0x07F8)

/* MSVDX_VEC_AVS, CR_VEC_AVS_BE_BASE_ADDR_COL_PIC, AVS_COL_PIC_PARAMS_BASE_ADDRESS
*/
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_AVS_COL_PIC_PARAMS_BASE_ADDRESS_MASK		(0xFFFFF000)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_AVS_COL_PIC_PARAMS_BASE_ADDRESS_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_AVS_COL_PIC_PARAMS_BASE_ADDRESS_SHIFT		(12)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_AVS_COL_PIC_PARAMS_BASE_ADDRESS_LENGTH		(20)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_AVS_COL_PIC_PARAMS_BASE_ADDRESS_DEFAULT		(0)
#define MSVDX_VEC_AVS_CR_VEC_AVS_BE_BASE_ADDR_COL_PIC_AVS_COL_PIC_PARAMS_BASE_ADDRESS_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_VEC_AVS_REG_IO2_H__ */
