/*!
 *****************************************************************************
 *
 * @File       msvdx_vec_vp6_reg_io2.h
 * @Description    This file contains the MSVDX_VEC_VP6_REG_IO2_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_VEC_VP6_REG_IO2_H__)
#define __MSVDX_VEC_VP6_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_OFFSET		(0x0258)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_STRIDE		(4)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_NO_ENTRIES		(32)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_SCAN, SCAN_1
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_1_MASK		(0x00003F00)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_1_LSBMASK		(0x0000003F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_1_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_1_LENGTH		(6)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_1_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_SCAN, SCAN_0
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_0_MASK		(0x0000003F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_0_LSBMASK		(0x0000003F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_0_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_0_LENGTH		(6)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_0_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_SCAN_SCAN_0_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_OFFSET		(0x0200)

/* MSVDX_VEC_VP6, CR_VEC_VP6_FE_PIC0, VP6_FE_FRAME_TYPE
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_MASK		(0x00000100)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC0_VP6_FE_FRAME_TYPE_ENUM {
	MSVDX_VEC_VP6_VP6_FE_FRAME_TYPE_INTER = 0x1,
	MSVDX_VEC_VP6_VP6_FE_FRAME_TYPE_INTRA = 0x0,
};

#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_OFFSET		(0x0204)

/* MSVDX_VEC_VP6, CR_VEC_VP6_FE_PIC1, VP6_FE_PIC_HEIGHT_IN_MBS_LESS1
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_HEIGHT_IN_MBS_LESS1_MASK		(0x0000FF00)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_HEIGHT_IN_MBS_LESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_HEIGHT_IN_MBS_LESS1_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_HEIGHT_IN_MBS_LESS1_LENGTH		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_HEIGHT_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_HEIGHT_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_FE_PIC1, VP6_FE_PIC_WIDTH_IN_MBS_LESS1
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_WIDTH_IN_MBS_LESS1_MASK		(0x000000FF)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_WIDTH_IN_MBS_LESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_WIDTH_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_WIDTH_IN_MBS_LESS1_LENGTH		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_WIDTH_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC1_VP6_FE_PIC_WIDTH_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_OFFSET		(0x0208)

/* MSVDX_VEC_VP6, CR_VEC_VP6_FE_PIC2, VP6_FE_USE_HUFF
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_USE_HUFF_MASK		(0x00010000)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_USE_HUFF_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_USE_HUFF_SHIFT		(16)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_USE_HUFF_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_USE_HUFF_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_USE_HUFF_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_FE_PIC2, VP6_FE_DECODE_COEFFS
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_COEFFS_MASK		(0x00000100)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_COEFFS_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_COEFFS_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_COEFFS_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_COEFFS_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_COEFFS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_FE_PIC2, VP6_FE_DECODE_PRED
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_PRED_MASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_PRED_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_PRED_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_PRED_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_PRED_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_FE_PIC2_VP6_FE_DECODE_PRED_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_OFFSET		(0x0250)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_PIC0, VP6_BE_FRAME_TYPE
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_FRAME_TYPE_MASK		(0x00000100)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_FRAME_TYPE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_FRAME_TYPE_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_FRAME_TYPE_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_FRAME_TYPE_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_FRAME_TYPE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_PIC0, VP6_BE_DCT_Q_MASK
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_DCT_Q_MASK_MASK		(0x0000003F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_DCT_Q_MASK_LSBMASK		(0x0000003F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_DCT_Q_MASK_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_DCT_Q_MASK_LENGTH		(6)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_DCT_Q_MASK_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC0_VP6_BE_DCT_Q_MASK_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_OFFSET		(0x0254)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_PIC1, VP6_BE_PIC_HEIGHT_IN_MBS_LESS1
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_HEIGHT_IN_MBS_LESS1_MASK		(0x00007F00)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_HEIGHT_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_HEIGHT_IN_MBS_LESS1_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_HEIGHT_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_HEIGHT_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_HEIGHT_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_PIC1, VP6_BE_PIC_WIDTH_IN_MBS_LESS1
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_WIDTH_IN_MBS_LESS1_MASK		(0x0000007F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_WIDTH_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_WIDTH_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_WIDTH_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_WIDTH_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC1_VP6_BE_PIC_WIDTH_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_OFFSET		(0x02E0)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_PIC2, VP6_BE_DECODE_COEFFS
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_COEFFS_MASK		(0x00000100)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_COEFFS_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_COEFFS_SHIFT		(8)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_COEFFS_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_COEFFS_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_COEFFS_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_PIC2, VP6_BE_DECODE_PRED
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_PRED_MASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_PRED_LSBMASK		(0x00000001)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_PRED_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_PRED_LENGTH		(1)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_PRED_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_PIC2_VP6_BE_DECODE_PRED_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_OFFSET		(0x02F0)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR, VP6_BE_DP_BUFFER_VLR_BASE_ADDR
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_MASK		(0x00000FFF)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_LSBMASK		(0x00000FFF)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_SHIFT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_LENGTH		(12)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_VP6_BE_DP_BUFFER_VLR_BASE_ADDR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_OFFSET		(0x02F8)

/* MSVDX_VEC_VP6, CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC, VP6_BE_BASE_ADDR_1STPART_PIC
*/
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_VP6_BE_BASE_ADDR_1STPART_PIC_MASK		(0xFFFFF000)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_VP6_BE_BASE_ADDR_1STPART_PIC_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_VP6_BE_BASE_ADDR_1STPART_PIC_SHIFT		(12)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_VP6_BE_BASE_ADDR_1STPART_PIC_LENGTH		(20)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_VP6_BE_BASE_ADDR_1STPART_PIC_DEFAULT		(0)
#define MSVDX_VEC_VP6_CR_VEC_VP6_BE_BASE_ADDR_1STPART_PIC_VP6_BE_BASE_ADDR_1STPART_PIC_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_VEC_VP6_REG_IO2_H__ */
