/*!
 *****************************************************************************
 *
 * @File       msvdx_rendec_mtx_slice_cntrl_reg_io2.h
 * @Description    This file contains the MSVDX_RENDEC_MTX_SLICE_CNTRL_REG_IO2_H Definitions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called "GPLHEADER" included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/


#if !defined (__MSVDX_RENDEC_MTX_SLICE_CNTRL_REG_IO2_H__)
#define __MSVDX_RENDEC_MTX_SLICE_CNTRL_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define RENDEC_SLICE_INFO_SL_HDR_CK_START_OFFSET		(0x0000)

/* RENDEC_SLICE_INFO, SL_HDR_CK_START, SL_NUM_SYMBOLS_LESS1
*/
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_NUM_SYMBOLS_LESS1_MASK		(0x07FF0000)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_NUM_SYMBOLS_LESS1_LSBMASK		(0x000007FF)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_NUM_SYMBOLS_LESS1_SHIFT		(16)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_NUM_SYMBOLS_LESS1_LENGTH		(11)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_NUM_SYMBOLS_LESS1_DEFAULT		(0)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_NUM_SYMBOLS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* RENDEC_SLICE_INFO, SL_HDR_CK_START, SL_ROUTING_INFO
*/
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ROUTING_INFO_MASK		(0x00000018)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ROUTING_INFO_LSBMASK		(0x00000003)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ROUTING_INFO_SHIFT		(3)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ROUTING_INFO_LENGTH		(2)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ROUTING_INFO_DEFAULT		(0)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ROUTING_INFO_SIGNED_FIELD	(IMG_FALSE)

/* RENDEC_SLICE_INFO, SL_HDR_CK_START, SL_ENCODING_METHOD
*/
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ENCODING_METHOD_MASK		(0x00000007)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ENCODING_METHOD_LSBMASK		(0x00000007)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ENCODING_METHOD_SHIFT		(0)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ENCODING_METHOD_LENGTH		(3)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ENCODING_METHOD_DEFAULT		(0)
#define RENDEC_SLICE_INFO_SL_HDR_CK_START_SL_ENCODING_METHOD_SIGNED_FIELD	(IMG_FALSE)

#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_OFFSET		(0x0004)

/* RENDEC_SLICE_INFO, SL_HDR_CK_PARAMS, SL_DATA
*/
#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_SL_DATA_MASK		(0xFFFFFFFF)
#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_SL_DATA_LSBMASK		(0xFFFFFFFF)
#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_SL_DATA_SHIFT		(0)
#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_SL_DATA_LENGTH		(32)
#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_SL_DATA_DEFAULT		(0)
#define RENDEC_SLICE_INFO_SL_HDR_CK_PARAMS_SL_DATA_SIGNED_FIELD	(IMG_FALSE)

#define RENDEC_SLICE_INFO_CK_HDR_OFFSET		(0x0008)

/* RENDEC_SLICE_INFO, CK_HDR, CK_START_ADDRESS_EXT
*/
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_EXT_MASK		(0x30000000)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_EXT_LSBMASK		(0x00000003)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_EXT_SHIFT		(28)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_EXT_LENGTH		(2)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_EXT_DEFAULT		(0)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_EXT_SIGNED_FIELD	(IMG_FALSE)

/* RENDEC_SLICE_INFO, CK_HDR, CK_NUM_SYMBOLS_LESS1
*/
#define RENDEC_SLICE_INFO_CK_HDR_CK_NUM_SYMBOLS_LESS1_MASK		(0x07FF0000)
#define RENDEC_SLICE_INFO_CK_HDR_CK_NUM_SYMBOLS_LESS1_LSBMASK		(0x000007FF)
#define RENDEC_SLICE_INFO_CK_HDR_CK_NUM_SYMBOLS_LESS1_SHIFT		(16)
#define RENDEC_SLICE_INFO_CK_HDR_CK_NUM_SYMBOLS_LESS1_LENGTH		(11)
#define RENDEC_SLICE_INFO_CK_HDR_CK_NUM_SYMBOLS_LESS1_DEFAULT		(0)
#define RENDEC_SLICE_INFO_CK_HDR_CK_NUM_SYMBOLS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* RENDEC_SLICE_INFO, CK_HDR, CK_START_ADDRESS
*/
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_MASK		(0x0000FFF0)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_LSBMASK		(0x00000FFF)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_SHIFT		(4)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_LENGTH		(12)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_DEFAULT		(0)
#define RENDEC_SLICE_INFO_CK_HDR_CK_START_ADDRESS_SIGNED_FIELD	(IMG_FALSE)

/* RENDEC_SLICE_INFO, CK_HDR, CK_ENCODING_METHOD
*/
#define RENDEC_SLICE_INFO_CK_HDR_CK_ENCODING_METHOD_MASK		(0x00000007)
#define RENDEC_SLICE_INFO_CK_HDR_CK_ENCODING_METHOD_LSBMASK		(0x00000007)
#define RENDEC_SLICE_INFO_CK_HDR_CK_ENCODING_METHOD_SHIFT		(0)
#define RENDEC_SLICE_INFO_CK_HDR_CK_ENCODING_METHOD_LENGTH		(3)
#define RENDEC_SLICE_INFO_CK_HDR_CK_ENCODING_METHOD_DEFAULT		(0)
#define RENDEC_SLICE_INFO_CK_HDR_CK_ENCODING_METHOD_SIGNED_FIELD	(IMG_FALSE)

#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_OFFSET		(0x000C)

/* RENDEC_SLICE_INFO, SLICE_SEPARATOR, SL_SEP_SUFFIX
*/
#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_SL_SEP_SUFFIX_MASK		(0x00000007)
#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_SL_SEP_SUFFIX_LSBMASK		(0x00000007)
#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_SL_SEP_SUFFIX_SHIFT		(0)
#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_SL_SEP_SUFFIX_LENGTH		(3)
#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_SL_SEP_SUFFIX_DEFAULT		(0)
#define RENDEC_SLICE_INFO_SLICE_SEPARATOR_SL_SEP_SUFFIX_SIGNED_FIELD	(IMG_FALSE)

#define RENDEC_SLICE_INFO_CK_GENERIC_OFFSET		(0x0010)

/* RENDEC_SLICE_INFO, CK_GENERIC, CK_HW_CODE
*/
#define RENDEC_SLICE_INFO_CK_GENERIC_CK_HW_CODE_MASK		(0x0000FFFF)
#define RENDEC_SLICE_INFO_CK_GENERIC_CK_HW_CODE_LSBMASK		(0x0000FFFF)
#define RENDEC_SLICE_INFO_CK_GENERIC_CK_HW_CODE_SHIFT		(0)
#define RENDEC_SLICE_INFO_CK_GENERIC_CK_HW_CODE_LENGTH		(16)
#define RENDEC_SLICE_INFO_CK_GENERIC_CK_HW_CODE_DEFAULT		(0)
#define RENDEC_SLICE_INFO_CK_GENERIC_CK_HW_CODE_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_RENDEC_MTX_SLICE_CNTRL_REG_IO2_H__ */
